#!/bin/bash

# PR been merged on github?  This will checkout $1 || develop, git pull, and then delete the branch you were on.

# Thanks http://stackoverflow.com/a/1593487/328817
branch_name="$(git symbolic-ref -q --short HEAD 2>/dev/null)" || branch_name="(unnamed branch)"; # detached HEAD

if [ "$branch_name" = "develop" ] || [ "$branch_name" = "master" ]
then
    echo "Only for feature branches!";
    exit 1;
fi

target_branch="$1"
if [ -z "$target_branch" ]
then
    target_branch="develop";
fi

git checkout $target_branch
if [ "$?" != "0" ]
then
    exit 1;
fi

git pull
git branch -d $branch_name
if [ "$?" != "0" ]
then
    exit 1;
fi

echo
remote=$(git config branch.${target_branch}.remote);
git remote prune $remote;

echo
echo 'Remaining branches:'
git branch
