#!/usr/bin/env php
<?php

$arguments = array_slice($argv, 1);

if (in_array('--help', $arguments) || in_array('-h', $arguments)) {
    echo 'NAME', PHP_EOL;
    echo '    git-dead-branch - List/delete branches that are contained in develop/master.', PHP_EOL;
    echo PHP_EOL;
    echo 'SYNOPSIS', PHP_EOL;
    echo '    git-dead-branch [-a] [-c] [-f]', PHP_EOL;
    echo PHP_EOL;
    echo 'OPTIONS', PHP_EOL;
    echo PHP_EOL;
    echo '    -h, --help', PHP_EOL;
    echo '        This help text.', PHP_EOL;
    echo PHP_EOL;
    echo '    -a, --all', PHP_EOL;
    echo '        Include remote branches.', PHP_EOL;
    echo PHP_EOL;
    echo '    -c, --cleanup', PHP_EOL;
    echo '        Automatically delete redundant branches.', PHP_EOL;
    echo PHP_EOL;
    echo '    -f, --force', PHP_EOL;
    echo '        Forces deletion of redundant branches.', PHP_EOL;
    return;
}

// Get all the local branches.
$branches = explode(PHP_EOL, rtrim(shell_exec('git branch')));

$deadBranches = array();

foreach ($branches as $branch) {
    // Remove leading '* ' or '  '.
    $branch = substr($branch, 2);

    // Ignore develop and master.
    if ($branch == 'develop' || $branch == 'master') {
        continue;
    }

    $containingBranches = array_map(
        function ($b) {
            // Remove leading '* ' or '  '.
            return substr($b, 2);
        },
        explode(PHP_EOL, rtrim(shell_exec('git branch --contains ' . escapeshellarg($branch))))
    );

    foreach ($containingBranches as $containingBranch) {
        if ($containingBranch == 'develop' || $containingBranch == 'master') {
            $deadBranches[] = $branch;
            break;
        }
    }
}

if (!$deadBranches) {
    echo 'There are no dead branches.', PHP_EOL;
} else {
    $cleanup = (in_array('--cleanup', $arguments) || in_array('-c', $arguments));
    $force = (in_array('--force', $arguments) || in_array('-f', $arguments));

    foreach ($deadBranches as $branch) {
        if ($cleanup) {
            $option = $force ? '-D' : '-d';
            echo shell_exec('git branch ' . $option . ' ' . escapeshellarg($branch));
        } else {
            echo $branch, PHP_EOL;
        }
    }
}
