#!/usr/bin/env php
<?php

$arguments = array_slice($argv, 1);

if (in_array('--help', $arguments) || in_array('-h', $arguments)) {
    echo 'NAME', PHP_EOL;
    echo '    git-dead-branch - List/delete branches that are contained in develop/master.', PHP_EOL;
    echo PHP_EOL;
    echo 'SYNOPSIS', PHP_EOL;
    echo '    git-dead-branch [-a] [-c] [-f]', PHP_EOL;
    echo PHP_EOL;
    echo 'OPTIONS', PHP_EOL;
    echo PHP_EOL;
    echo '    -h, --help', PHP_EOL;
    echo '        This help text.', PHP_EOL;
    echo PHP_EOL;
    echo '    -a, --all', PHP_EOL;
    echo '        Include remote branches.', PHP_EOL;
    echo PHP_EOL;
    echo '    -c, --cleanup', PHP_EOL;
    echo '        Automatically delete redundant branches.', PHP_EOL;
    echo PHP_EOL;
    echo '    -f, --force', PHP_EOL;
    echo '        Forces deletion of redundant branches.', PHP_EOL;
    return;
}

// Get the branches.
$allBranches = (in_array('-a', $arguments) || in_array('--all', $arguments));
if ($allBranches) {
    $branches = explode(PHP_EOL, rtrim(shell_exec('git branch -a')));
    $branches = array_filter($branches, function ($branch) {
        return strpos($branch, '->') === false;
    });
} else {
    $branches = explode(PHP_EOL, rtrim(shell_exec('git branch')));
}

$deadBranches = array();

define('DEVELOP_MASTER_PATTERN', '/^(remotes\/[^\/]+\/)?(develop|master)$/');

foreach ($branches as $branch) {
    // Remove leading '* ' or '  '.
    $branch = substr($branch, 2);

    // Ignore local and remote develop and master.
    if (preg_match(DEVELOP_MASTER_PATTERN, $branch)) {
        continue;
    }

    if ($allBranches) {
        $containingBranchesCommand = 'git branch -a --contains ' . escapeshellarg($branch);
    } else {
        $containingBranchesCommand = 'git branch --contains ' . escapeshellarg($branch);
    }

    $containingBranches = array_map(
        function ($b) {
            // Remove leading '* ' or '  '.
            return substr($b, 2);
        },
        explode(PHP_EOL, rtrim(shell_exec($containingBranchesCommand)))
    );

    foreach ($containingBranches as $containingBranch) {
        if (preg_match(DEVELOP_MASTER_PATTERN, $containingBranch)) {
            $deadBranches[] = $branch;
            break;
        }
    }
}

if (!$deadBranches) {
    echo 'There are no dead branches.', PHP_EOL;
} else {
    $cleanup = (in_array('--cleanup', $arguments) || in_array('-c', $arguments));
    $force = (in_array('--force', $arguments) || in_array('-f', $arguments));

    if ($allBranches && $cleanup) {
        echo 'Cleaning up remote branches is not currently supported.', PHP_EOL;
        $cleanup = false;
    }

    foreach ($deadBranches as $branch) {
        if ($cleanup) {
            $option = $force ? '-D' : '-d';
            echo shell_exec('git branch ' . $option . ' ' . escapeshellarg($branch));
        } else {
            echo $branch, PHP_EOL;
        }
    }
}
